# https://taskfile.dev

version: "3"

vars:
  VERSION: 0.0.1

tasks:
  run: go run -ldflags "-X main.version={{.VERSION}}" .
  build: go build -ldflags "-X main.version={{.VERSION}}" .
  install: go build -ldflags "-X main.version={{.VERSION}}" -o /usr/local/bin/loop .
